### ISSUE TITLE
Few More Items

### ISSUE THREAD

**Issue by aaronksaunders** [juarezpaf/ionic-adventures#22]
https://github.com/aaronksaunders/parse-starter-ionic

http://www.clearlyinnovative.com/ionic-framework-facebook-login-with-parse/

http://www.clearlyinnovative.com/ionic-framework-camera-image-uploads-and-base64-strings/

**Comment by juarezpaf** [comment]
Thanks for your contribution @aaronksaunders 
I'm going to insert these ones tonight. :rocket:
